# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(839, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainLayout = QtWidgets.QVBoxLayout()
        self.MainLayout.setObjectName("MainLayout")
        self.imagesLayout = QtWidgets.QHBoxLayout()
        self.imagesLayout.setObjectName("imagesLayout")
        self.Original_Layout = QtWidgets.QVBoxLayout()
        self.Original_Layout.setObjectName("Original_Layout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.Original_Layout.addWidget(self.label)
        self.original_image = clickable_qlable(self.centralwidget)
        self.original_image.setText("")
        self.original_image.setObjectName("original_image")
        self.Original_Layout.addWidget(self.original_image)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2.setStretch(1, 3)
        self.Original_Layout.addLayout(self.horizontalLayout_2)
        self.Original_Layout.setStretch(1, 6)
        self.Original_Layout.setStretch(2, 1)
        self.imagesLayout.addLayout(self.Original_Layout)
        self.WatermarkedLayout = QtWidgets.QVBoxLayout()
        self.WatermarkedLayout.setObjectName("WatermarkedLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.WatermarkedLayout.addWidget(self.label_4)
        self.watermarked_image = clickable_qlable(self.centralwidget)
        self.watermarked_image.setText("")
        self.watermarked_image.setObjectName("watermarked_image")
        self.WatermarkedLayout.addWidget(self.watermarked_image)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.watermarked_psnr = QtWidgets.QLabel(self.centralwidget)
        self.watermarked_psnr.setObjectName("watermarked_psnr")
        self.horizontalLayout_5.addWidget(self.watermarked_psnr)
        self.horizontalLayout_5.setStretch(1, 3)
        self.WatermarkedLayout.addLayout(self.horizontalLayout_5)
        self.WatermarkedLayout.setStretch(1, 6)
        self.WatermarkedLayout.setStretch(2, 1)
        self.imagesLayout.addLayout(self.WatermarkedLayout)
        self.MainLayout.addLayout(self.imagesLayout)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.key_box = QtWidgets.QSpinBox(self.centralwidget)
        self.key_box.setMinimum(1000)
        self.key_box.setMaximum(10000000)
        self.key_box.setProperty("value", 3389)
        self.key_box.setObjectName("key_box")
        self.horizontalLayout_3.addWidget(self.key_box)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.search_box = QtWidgets.QSpinBox(self.centralwidget)
        self.search_box.setMinimum(1)
        self.search_box.setMaximum(63)
        self.search_box.setProperty("value", 63)
        self.search_box.setObjectName("search_box")
        self.horizontalLayout_6.addWidget(self.search_box)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.outputkey_field = QtWidgets.QLineEdit(self.centralwidget)
        self.outputkey_field.setText("")
        self.outputkey_field.setReadOnly(True)
        self.outputkey_field.setObjectName("outputkey_field")
        self.horizontalLayout_7.addWidget(self.outputkey_field)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.MainLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_btn.setAutoDefault(False)
        self.update_btn.setDefault(False)
        self.update_btn.setFlat(False)
        self.update_btn.setObjectName("update_btn")
        self.horizontalLayout_10.addWidget(self.update_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setObjectName("load_btn")
        self.horizontalLayout_9.addWidget(self.load_btn)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setAutoFillBackground(False)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_9.addWidget(self.save_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.MainLayout.addLayout(self.verticalLayout_6)
        self.MainLayout.setStretch(0, 2)
        self.MainLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.MainLayout)
        self.loadingBar = QtWidgets.QProgressBar(self.centralwidget)
        self.loadingBar.setProperty("value", 0)
        self.loadingBar.setOrientation(QtCore.Qt.Vertical)
        self.loadingBar.setObjectName("loadingBar")
        self.horizontalLayout.addWidget(self.loadingBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSet_Watermark = QtWidgets.QAction(MainWindow)
        self.actionSet_Watermark.setObjectName("actionSet_Watermark")
        self.actionExtract_Visualizer = QtWidgets.QAction(MainWindow)
        self.actionExtract_Visualizer.setObjectName("actionExtract_Visualizer")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionSet_Watermark)
        self.menuFile.addAction(self.actionExtract_Visualizer)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Watermarking Program"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">ORIGINAL</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">WATERMAKED</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">PSNR :</span></p></body></html>"))
        self.watermarked_psnr.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">0</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">KEY</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">POSITION</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">OUTPUT KEY</span></p></body></html>"))
        self.update_btn.setText(_translate("MainWindow", "Update"))
        self.load_btn.setText(_translate("MainWindow", "Load Image"))
        self.save_btn.setText(_translate("MainWindow", "Save Image"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSet_Watermark.setText(_translate("MainWindow", "Set Watermark"))
        self.actionExtract_Visualizer.setText(_translate("MainWindow", "Extract Visualizer"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
from clickable_qlable import clickable_qlable
