# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(848, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainLayout = QtWidgets.QVBoxLayout()
        self.MainLayout.setObjectName("MainLayout")
        self.imagesLayout = QtWidgets.QHBoxLayout()
        self.imagesLayout.setObjectName("imagesLayout")
        self.Original_Layout = QtWidgets.QVBoxLayout()
        self.Original_Layout.setObjectName("Original_Layout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.Original_Layout.addWidget(self.label)
        self.image_toreverse = clickable_qlable(self.centralwidget)
        self.image_toreverse.setText("")
        self.image_toreverse.setObjectName("image_toreverse")
        self.Original_Layout.addWidget(self.image_toreverse)
        self.Original_Layout.setStretch(1, 6)
        self.imagesLayout.addLayout(self.Original_Layout)
        self.WatermarkedLayout = QtWidgets.QVBoxLayout()
        self.WatermarkedLayout.setObjectName("WatermarkedLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.WatermarkedLayout.addWidget(self.label_4)
        self.extracted_watermark = clickable_qlable(self.centralwidget)
        self.extracted_watermark.setText("")
        self.extracted_watermark.setObjectName("extracted_watermark")
        self.WatermarkedLayout.addWidget(self.extracted_watermark)
        self.WatermarkedLayout.setStretch(1, 6)
        self.imagesLayout.addLayout(self.WatermarkedLayout)
        self.MainLayout.addLayout(self.imagesLayout)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.inputkey_field = QtWidgets.QLineEdit(self.centralwidget)
        self.inputkey_field.setText("")
        self.inputkey_field.setReadOnly(False)
        self.inputkey_field.setObjectName("inputkey_field")
        self.horizontalLayout_7.addWidget(self.inputkey_field)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.force_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.force_checkbox.setObjectName("force_checkbox")
        self.horizontalLayout_2.addWidget(self.force_checkbox)
        self.resized_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.resized_checkbox.setEnabled(False)
        self.resized_checkbox.setObjectName("resized_checkbox")
        self.horizontalLayout_2.addWidget(self.resized_checkbox)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.MainLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.extract_btn = QtWidgets.QPushButton(self.centralwidget)
        self.extract_btn.setAutoDefault(False)
        self.extract_btn.setDefault(False)
        self.extract_btn.setFlat(False)
        self.extract_btn.setObjectName("extract_btn")
        self.horizontalLayout_10.addWidget(self.extract_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setObjectName("load_btn")
        self.horizontalLayout_9.addWidget(self.load_btn)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setAutoFillBackground(False)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_9.addWidget(self.save_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.MainLayout.addLayout(self.verticalLayout_6)
        self.MainLayout.setStretch(0, 2)
        self.MainLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.MainLayout)
        self.loadingBar = QtWidgets.QProgressBar(self.centralwidget)
        self.loadingBar.setProperty("value", 0)
        self.loadingBar.setOrientation(QtCore.Qt.Vertical)
        self.loadingBar.setObjectName("loadingBar")
        self.horizontalLayout.addWidget(self.loadingBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSet_Watermark = QtWidgets.QAction(MainWindow)
        self.actionSet_Watermark.setObjectName("actionSet_Watermark")
        self.actionExtract_Visualizer = QtWidgets.QAction(MainWindow)
        self.actionExtract_Visualizer.setObjectName("actionExtract_Visualizer")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Extracting Program"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">WATERMARKED</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">WATERMARK</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">INPUT KEY</span></p></body></html>"))
        self.force_checkbox.setText(_translate("MainWindow", "Force Extract"))
        self.resized_checkbox.setText(_translate("MainWindow", "is Resized ?"))
        self.extract_btn.setText(_translate("MainWindow", "Extract"))
        self.load_btn.setText(_translate("MainWindow", "Load Image"))
        self.save_btn.setText(_translate("MainWindow", "Save Image"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSet_Watermark.setText(_translate("MainWindow", "Set Watermark"))
        self.actionExtract_Visualizer.setText(_translate("MainWindow", "Extract Visualizer"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
from clickable_qlable import clickable_qlable
